env:
  name: "orbit_wars"
  board_size: 100.0
  episode_steps: 500
  candidate_count: 8
  ship_bucket_count: 8
  max_planets: 48
  max_ships: 400.0
  max_production: float = 5.0
  env_args:
    configuration: {"seed": 42}
    debug: True

logging:
  project_name: "Orbit Wars"
  task_name: "Train DQN Agent"

model:
  model_path: "./orbit_wars_checkpoint"
  model_name: "NearestPlanetAgent"
  model_args:
    # model_name: "fasternet_t1.in1k"
    # pretrained: True
    # img_size: 384
    name: "NearestPlanetAgent"

loss:
  loss_name: "InfoNCE"
  loss_args:
    # Loss
    label_smoothing: 0.1

eval:
  # Eval
  eval_episodes: 10
  eval_every_n_epoch: 1        # eval every n Epoch
  normalize_features: True
  eval_reference_n: -1             # -1 for all or int

training:
  # Training 
  mixed_precision: False
  custom_sampling: True        
  seed: 1
  epochs: 20
  batch_size: 32              
  verbose: True
  gpu_ids: [0,]           # GPU ids for training

  # Hard negative sampling
  sim_sample: False

  # Optimizer 
  clip_grad: 100                     # None | float
  decay_exclude_bias: False
  grad_checkpointing: False     # Gradient Checkpointing
  
  # Learning Rate
  lr: 1e-4                    # 1 * 10^-4 for ViT | 1 * 10^-1 for CNN
  scheduler: "cosine"           # "polynomial" | "cosine" | "constant" | None
  warmup_epochs: 1
  lr_end: 0.0001               #  only for "polynomial"
  
  # Augment Images
  prob_flip: 0.5              # flipping the sat image and drone image simultaneously
  
  # Eval before training
  zero_shot: False
  
  # Checkpoint to start from
  checkpoint_start: null
  # checkpoint_start: "/home/tts26/sonh/university_checkpoint/SiameseNetwork/20260329_094234/weights_e11_86.5962.pth"

  # set num_workers to 0 if on Windows
  num_workers: 8
  
  # for better performance
  cudnn_benchmark: True
  
  # make cudnn deterministic
  cudnn_deterministic: False
